# Generated by Django 4.2.6 on 2023-10-15 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("transactions", "0001_initial"),
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.transaction",
            ),
        ),
    ]
