# Generated by Django 4.2.6 on 2023-10-15 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0003_client_statiton_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="statiton_number",
            new_name="station_number",
        ),
    ]
