# Generated by Django 4.2.6 on 2023-10-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0004_rename_statiton_number_client_station_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="member_status",
            field=models.CharField(
                choices=[
                    ("non permanent", "non permanent"),
                    ("permanant", "Permanant"),
                ],
                max_length=50,
            ),
        ),
    ]
