# Generated by Django 4.2.6 on 2023-10-17 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0005_alter_client_member_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="status",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="client.client"
            ),
        ),
    ]
