# Generated by Django 4.2.6 on 2023-10-17 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0006_account_status_alter_account_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="client.client"
            ),
        ),
    ]
