# Generated by Django 4.2.6 on 2023-10-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0010_alter_client_station_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="member_status",
            field=models.CharField(
                choices=[("non permanent", "non permanent"), ("permanent", "Permanent")], max_length=50
            ),
        ),
    ]
