# Generated by Django 4.2.6 on 2023-10-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0011_alter_client_member_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="workstation",
            name="type",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
    ]
