# Generated by Django 4.2.6 on 2023-10-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0012_workstation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
