# Generated by Django 4.2.6 on 2023-10-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensecancellation",
            name="reason",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
