# Generated by Django 4.2.6 on 2023-10-17 20:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_remove_transaction_client_and_more"),
        ("transactions", "0002_transaction_amount_currency_transaction_owing_and_more"),
    ]

    operations = []
