# Generated by Django 4.2.6 on 2023-10-17 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0007_alter_account_client"),
        ("transactions", "0003_merge_20231017_2031"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="client",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="client.client",
            ),
            preserve_default=False,
        ),
    ]
