# Generated by Django 4.2.6 on 2023-10-27 10:27

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0004_transaction_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="owing",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=2, default=Decimal("0"), default_currency="USD", max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="resource",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="transactions.resource"
            ),
        ),
    ]
