# Generated by Django 4.2.6 on 2023-10-31 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0007_resource_price_currency_alter_resource_price"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Resource",
            new_name="Product",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="resource",
            new_name="product",
        ),
    ]
