# Generated by Django 4.2.6 on 2023-10-31 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0008_rename_resource_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="note",
        ),
    ]
