# Generated by Django 4.2.6 on 2023-11-01 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0013_alter_client_count"),
        ("transactions", "0009_remove_transaction_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="work_station",
            field=models.OneToOneField(
                blank=True, default="", on_delete=django.db.models.deletion.CASCADE, to="client.workstation"
            ),
            preserve_default=False,
        ),
    ]
