# Generated by Django 4.2.6 on 2023-11-01 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0010_transaction_work_station"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="work_station",
        ),
    ]
