# Generated by Django 4.2.6 on 2023-11-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0015_alter_transaction_work_station"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(default="", max_length=10),
        ),
    ]
