# Generated by Django 4.2.6 on 2023-11-02 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0013_alter_client_count"),
        ("transactions", "0016_transaction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="work_station",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="client.workstation"
            ),
        ),
    ]
