# Generated by Django 4.2.6 on 2023-11-01 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("client", "0013_alter_client_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="voucherCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="voucherFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("file", models.FileField(upload_to="vouchers")),
                ("date_created", models.DateField(auto_now_add=True)),
                ("status", models.CharField(default="not populated", max_length=50)),
                (
                    "category",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="vouchers.vouchercategory"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="voucherTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=50)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("start_time", models.TimeField(auto_now_add=True)),
                ("end_time", models.TimeField()),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="client.client")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="vouchers",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("voucher_no", models.CharField(max_length=50)),
                ("date_created", models.DateField(auto_now_add=True)),
                ("date_used", models.DateField(auto_now=True)),
                ("status", models.CharField(default="unused", max_length=50)),
                ("file", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="vouchers.voucherfile")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
