# Generated by Django 4.2.6 on 2023-11-01 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0002_remove_vouchertransaction_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="vouchertransaction",
            name="vouch",
            field=models.OneToOneField(
                default="", on_delete=django.db.models.deletion.CASCADE, to="vouchers.vouchers"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vouchertransaction",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
