# Generated by Django 4.2.6 on 2023-11-01 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0013_alter_client_count"),
        ("vouchers", "0003_vouchertransaction_vouch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vouchertransaction",
            name="work_station",
            field=models.OneToOneField(
                blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to="client.workstation"
            ),
            preserve_default=False,
        ),
    ]
